// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Post struct {
	ID        string `json:"id"`
	Content   string `json:"content"`
	Timestamp string `json:"timestamp"`
	Author    *User  `json:"author"`
}

type Query struct {
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}
